replicaCount: 1

imagePullSecrets:
- name: beep-registry

image:
  repository: gitlab.polytech.umontpellier.fr:5050/beep/docs
  pullPolicy: Always
  tag: 056b6d57
  port: 3333

service:
  port: 3333
  type: ClusterIP

ingress:
  enabled: true
  annotations: {traefik.ingress.kubernetes.io/router.entrypoints: web}
  hosts:
  - host: 'if you see this, it means that the ingress is not working properly'
    paths: ['/']


