apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beep-docs.fullname" . }}
  labels:
    {{- include "beep-docs.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "beep-docs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beep-docs.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP