apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "beep-docs.fullname" .) }}
  labels:
    {{- include "beep-docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "beep-docs.selectorLabels" . | nindent 4 }}
